### PR TITLE
MGMT-8728: make assets a typed interface package with mock

### PR DESCRIPTION
**Pull request by yevgeny-shnaidman**

### CODE REVIEW

**Comment by ybettan** [comment]
nit:
"make assets a typed interface *package* with mock"

**Comment by yevgeny-shnaidman** [comment]
> nit: "make assets a typed interface _package_ with mock"

fixed

**Comment by ybettan** [comment]
Waiting for GHA to turn green (CI isn't waiting for it to merge) and I will lgtm

**Pull request merged**
