### PR TITLE
Update OSMajor and OSMajorMinor when multiple kernel versions are run…

### PR DESCRIPTION
**Pull request by Veritasosrb**
…ning in cluster. Refer issue 93 for more details.

### CODE REVIEW

**Comment by Veritasosrb** [comment]
@bthurber Failure in test e2e/test-e2e seems due to CRD terminating. From the logs could not see CRD deletion getting executed. Can we retry the test or check the setup why the CRD was in termination state.

**Review by bthurber — COMMENTED** [review]
/lgtm

**Pull request merged**
