### PR TITLE
Added parallel worflow

### PR DESCRIPTION
**Pull request by zvonkok**
Added parallel worflow
Enabled linter errors

### CODE REVIEW

**Comment by zvonkok** [comment]
@ArangoGutierrez @dagrayvid The OpenShift CI tests are still running.... We have now a version of github actions that do almost the same thing as the OpenShift CI.

**Comment by dagrayvid** [comment]
> @ArangoGutierrez @dagrayvid The OpenShift CI tests are still running.... We have now a version of github actions that do almost the same thing as the OpenShift CI.

The PR to remove these tests was merged. I wonder if it will be applied to new PR's, but not this one since it was created before the changes to the CI?

**Comment by ArangoGutierrez** [comment]
Yay now all works as expected
/lgtm

**Pull request merged**
