### PR TITLE
Move mocks to separate dir

### PR DESCRIPTION
**Pull request by pmtk**
PR moves mocks to separate directory inside `internal/`.
This change improves overall coverage (as reported by running `make unit-tests`) by 13.4% (`52.6 -> 65.9`).

### CODE REVIEW

**Comment by pmtk** [comment]
Detailed changes:
```
| pkg                  | before | after |
|----------------------+--------+-------|
| Cli Suite            | 100.0% |       |
| HelmCmGetter Suite   |  31.1% |       |
| Leaderelection Suite | 100.0% |       |
| Finalizers Suite     |  65.1% |       |
| State Suite          |  52.3% | 71.9% |
| Assets Suite         |   3.8% |  5.4% |
| Clients Suite        |   7.5% | 21.7% |
| Cluster Suite        |  65.8% | 96.1% |
| Filter Suite         |  83.9% |       |
| Helmer Suite         |  31.9% |       |
| Kernel Suite         |  43.3% | 65.0% |
| Lifecycle Suite      |  52.7% | 87.9% |
| Metrics Suite        |  23.1% |  100% |
| PollActions Suite    |  73.6% | 81.9% |
| Proxy Suite          |  57.3% | 81.0% |
| Resource Suite       |  61.9% | 65.5% |
| Scheme Suite         |  66.7% |       |
| State Suite          | 100.0% |       |
| Storage Suite        |  53.4% | 88.6% |
| Upgrade Suite        |  70.8% | 80.0% |
| utils tests          |  73.9% |       |
|----------------------+--------+-------|
| composite coverage   |  52.6% | 65.9% |
```

**Comment by ybettan** [comment]
@pmtk Can you please share the before and after relevant `tree` files so it is easier to understand where did the mocks moved?

**Comment by ybettan** [comment]
Also why did some of the packages had a certain cover-edge and don't have it anymore?

**Comment by pmtk** [comment]
> Also why did some of the packages had a certain cover-edge and don't have it anymore?

They still do. Sorry for the confusion: I put a number in the "after" column only if coverage increased, if the cell is empty, then the coverage stayed the same.

> @pmtk Can you please share the before and after relevant `tree` files so it is easier to understand where did the mocks moved?

Sure. This is before:
```
.
├── internal
│   └── controllers
│       └── state
│           ├── mock_clusteroperator_api.go
│           └── mock_statusupdater_api.go
└── pkg
    ├── assets
    │   └── mock_assets_api.go
    ├── clients
    │   └── mock_clients_api.go
    ├── cluster
    │   └── mock_cluster_api.go
    ├── kernel
    │   └── mock_kernel_api.go
    ├── lifecycle
    │   └── mock_lifecycle_api.go
    ├── metrics
    │   └── mock_metrics_api.go
    ├── poll
    │   └── mock_poll_api.go
    ├── proxy
    │   └── mock_proxy_api.go
    ├── registry
    │   └── mock_registry_api.go
    ├── resource
    │   └── mock_resource_api.go
    ├── storage
    │   └── mock_storage_api.go
    └── upgrade
        └── mock_upgrade_api.go

```

This is after:
```
.
└── internal
    └── mocks
        ├── mock_assets_api.go
        ├── mock_clients_api.go
        ├── mock_cluster_api.go
        ├── mock_clusteroperator_api.go
        ├── mock_kernel_api.go
        ├── mock_lifecycle_api.go
        ├── mock_metrics_api.go
        ├── mock_poll_api.go
        ├── mock_proxy_api.go
        ├── mock_registry_api.go
        ├── mock_resource_api.go
        ├── mock_statusupdater_api.go
        ├── mock_storage_api.go
        └── mock_upgrade_api.go
```

**Comment by qbarrand** [comment]
I think this change might make it trickier to understand which interface a mock is based on. If the concern is altered coverage numbers, do you think this could be solved by `grep -v` on the coverprofile file?

**Comment by pmtk** [comment]
> I think this change might make it trickier to understand which interface a mock is based on. If the concern is altered coverage numbers, do you think this could be solved by `grep -v` on the coverprofile file?

I found a comment that this might lead to inaccurate total coverage. I tested it: `grep -v` yields `65.3%` whereas relocating mocks yields `65.9%`. If that inaccuracies are something you're fine with (or keeping it as is), then I'm okay with closing this PR to not introduce confusion you mentioned.

**Comment by yevgeny-shnaidman** [comment]
> > I think this change might make it trickier to understand which interface a mock is based on. If the concern is altered coverage numbers, do you think this could be solved by `grep -v` on the coverprofile file?
> 
> I found a comment that this might lead to inaccurate total coverage. I tested it: `grep -v` yields `65.3%` whereas relocating mocks yields `65.9%`. If that inaccuracies are something you're fine with (or keeping it as is), then I'm okay with closing this PR to not introduce confusion you mentioned.

I think that for now we can live with such inaccuracy. It might matter once we move to k8s upstream, but we can leave the decision till then

**Pull request closed without merging**
