### PR TITLE
update the SRO image in the bundle

### PR DESCRIPTION
**Pull request by SchSeba**
The image that was in use before doesn't exist/is private on quay

Signed-off-by: Sebastian Sch <sebassch@gmail.com>

### CODE REVIEW

**Comment by SchSeba** [comment]
Hi @pacevedom thanks for the label.

is the lane failing a flake or something I miss in the files?

**Comment by pacevedom** [comment]
Its a weird sync condition that sometimes happens, a rerun should turn it into green.

**Pull request merged**
