### PR TITLE
MGMT-9164: Change the import path to the new repository

### PR DESCRIPTION
**Pull request by qbarrand**
Some references to PSAP remain in the base YAML files and the Helm charts, but those will be addressed in separate PRs for clarity.

### CODE REVIEW

**Comment by qbarrand** [comment]
[NFD uses the `sigs.k8s.io/node-feature-discovery` import path](https://github.com/kubernetes-sigs/node-feature-discovery/blob/master/cmd/nfd-master/main.go#L28) instead of the repo's URL. Hold until we clarify what should be used.

/hold

**Comment by zvonkok** [comment]
All [k8s.io/](http://k8s.io/) in golang resolves into [github.com/kubernetes/](http://github.com/kubernetes/)

And [sigs.k8s.io/](http://sigs.k8s.io/) to [github.com/kubernetes-sigs/](http://github.com/kubernetes-sigs/)

We use this in NFD and other sigs project also use the shorter URL. Just type `sig.k8s.io` into the browser and a redirect will get you to `github.com/kubernetes-sigs`

**Comment by ybettan** [comment]
@qbarrand What do we want to do with that PR?

**Comment by qbarrand** [comment]
It is on hold for now, let us leave it as is if that's okay.

**Comment by bthurber** [comment]
@qbarrand is this still needed?

**Comment by qbarrand** [comment]
Closing since we will not move this codebase upstream.

**Pull request closed without merging**
