### PR TITLE
Add pull secret management for DTK

### PR DESCRIPTION
**Pull request by pacevedom**
When deploying in GCP the crane package gets into an infinite loop if traffic towards metadata server is dropped. This makes SRO unresponsive.
Changing authn discovery from crane package into a manual approach where we grab the pull secrets from a secret will avoid the use of the metadata server while still being able to authenticate and obtain the same info.

* Add pull secret management

Signed-off-by: Pablo Acevedo Montserrat <pacevedo@redhat.com>

* Adjust vendor dependencies

* Update bundle for 4.9

### CODE REVIEW

**Comment by pacevedom** [comment]
cc @dagrayvid

**Comment by dagrayvid** [comment]
Seems like a potential github actions flake... trying again

/ok-to-test

**Comment by dagrayvid** [comment]
@pacevedom, seems like the e2e tests are running quite slow (and failing because of timeouts)... I suspect it's more related to the cluster using burstable t2/t3 instances than any of the included changes, but I would like to see a green test before proceeding.

/ok-to-test

**Pull request merged**
