### PR TITLE
Add silicom.dk and silicom.com domains to RBAC permissions.

### PR DESCRIPTION
**Pull request by rmr-silicom**

### CODE REVIEW

**Comment by williamcaban** [comment]
@bthurber @kpouget anything we can do to attend this?

**Review by bthurber — APPROVED** [review]
/lgtm

**Comment by novacain1** [comment]
thank you!  any idea when this could be present in the community version, which is what we're using on 4.8?

**Comment by bthurber** [comment]
> thank you! any idea when this could be present in the community version, which is what we're using on 4.8?

@dagrayvid do we need to create a backport BZ for this?

**Comment by bthurber** [comment]
> thank you! any idea when this could be present in the community version, which is what we're using on 4.8?

Cherry picked to master.

**Pull request merged**
