### PR TITLE
Simplifying CM handling for custom charts

### PR DESCRIPTION
**Pull request by zvonkok**
Now charts can be located "anywhere" to create a CM for testing and development. 
Left the helm helpers intact until we drop all internal charts. 

Added a watcher for CMs. If the custom chart is updated SRO should pick up the change and reconcile the new chart. 
Since the filter package will only trigger on owned objects, SRO will ignore other CM edits.

### CODE REVIEW

**Comment by qbarrand** [comment]
I like the watcher on ConfigMaps. For the chart part, would the [new script we just merged](https://github.com/openshift-psap/special-resource-operator/blob/master/scripts/make-cm-recipe) be useful?

**Comment by zvonkok** [comment]
@qbarrand Will take a look, one thing missing is the update of the `ownerReference` by creating the CM via kubectl it is not owned by the underlying special resource CR. 
The CM should be apply not create because when using the CM you would have a lot of updates during testing and development.

**Comment by zvonkok** [comment]
@qbarrand The script also misses the index.yaml file you need to include this one as well.

**Comment by zvonkok** [comment]
Furthermore the script misses the repository as well.

**Pull request closed without merging**
