### PR TITLE
Simplifying upstream deployment for vanilla k8s.

### PR DESCRIPTION
**Pull request by ybettan**
Also removing unnecessary code.

Signed-off-by: Yoni Bettan <ybettan@redhat.com>

### CODE REVIEW

**Comment by ybettan** [comment]
`k8s-e2e` GH workflow is supposed to fail as we removed the underlaying makefile target.

**Review by yevgeny-shnaidman — COMMENTED** [review]
LGTM. 
Lets just open ticket for deciding which method to use (helm or kustomize) and expolore if we might change the files on the fly ( kusotmize patches)

**Pull request merged**
