### PR TITLE
Add @pacevedom and @qbarrand as approvers

### PR DESCRIPTION
**Pull request by qbarrand**

### CODE REVIEW

**Review by bthurber — COMMENTED** [review]
Would it be beneficial to add as reviewers as well?  I expect we will add more team members such as Yoni and Yevgeny for reviewers.  May be worth doing that for this PR.

**Comment by qbarrand** [comment]
@bthurber @ybettan and @yevgeny-shnaidman are already reviewers: https://github.com/openshift-psap/special-resource-operator/blob/fd98ab8e02101fe1a451c86a4cf90bb6f01d79e7/OWNERS#L13-L14

**Review by bthurber — APPROVED** [review]

**Pull request merged**
