### PR TITLE
e2e deploy undeploy

### PR DESCRIPTION
**Pull request by zvonkok**
Added standalone deploy and undeploy go programs for easier handling.
Added some packages that we can use in SRO and the e2e test and other programs that we need.

### CODE REVIEW

**Review by dagrayvid — COMMENTED** [review]
Overall this looks good, I just need to test the deploy/undeploy before approving. One question/nit: Is the addition of the `test/deploy/deploy` binary file in the previous PR intentional? If not we should delete it in this PR.

**Review by ArangoGutierrez — APPROVED** [review]
tested on 4.6, both deploy and undeploy work as expected 
/lgtm

**Comment by ArangoGutierrez** [comment]
[test.log](https://github.com/openshift-psap/special-resource-operator/files/5690369/test.log)

**Comment by dagrayvid** [comment]
> Overall this looks good, I just need to test the deploy/undeploy before approving. One question/nit: Is the addition of the `test/deploy/deploy` binary file in the previous PR intentional? If not we should delete it in this PR.

Sorry, was confused. Glad to see that this PR deletes this file.

**Comment by dagrayvid** [comment]
Looks like a flakey e2e-aws-upgrade test. 
/retest

**Pull request merged**
