### PR TITLE
Adding github actions OpenShift CI CD Jobs

### PR DESCRIPTION
**Pull request by zvonkok**
First step of enabling our own CI/CD with github actions.
Makefile simplifications.
Separate CRD and CR creation for successful make deploy and make undeploy.
The pipeline runs now 
```
make verify
make unit
make lint
make test-e2e
```
for testing.

### CODE REVIEW

**Comment by ArangoGutierrez** [comment]
Let's wait for https://github.com/openshift/release/pull/14222 to be merged first
/hold

**Comment by dagrayvid** [comment]
It seems like the YAML linter is incorrectly reporting errors for the templatized YAML. Maybe we should disable the the braces related rules in the YAML linter?

**Comment by zvonkok** [comment]
Yep all things here need some love just getting started :)

**Comment by zvonkok** [comment]
All the commits are squashed. Looks clean now.

**Review by ArangoGutierrez — APPROVED** [review]
This Patch adds yaml linters and also updates the vendor folder
/lgtm

**Pull request merged**
